default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: logi_balance_development

test:
  <<: *default
  database: logi_balance_test

production:
  primary:
    <<: *default
    database: logi_balance_production
    username: <%= ENV.fetch("LOGI_BALANCE_DATABASE_USERNAME") %>
    password: <%= ENV.fetch("LOGI_BALANCE_DATABASE_PASSWORD") %>
    host: <%= ENV.fetch("LOGI_BALANCE_DATABASE_HOST") %>

  cache:
    <<: *default
    database: logi_balance_cache
    username: <%= ENV.fetch("LOGI_BALANCE_DATABASE_USERNAME") %>
    password: <%= ENV.fetch("LOGI_BALANCE_DATABASE_PASSWORD") %>
    host: <%= ENV.fetch("LOGI_BALANCE_DATABASE_HOST") %>
