default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: logi_balance_development

test:
  <<: *default
  database: logi_balance_test

production:
  primary: &production
    <<: *default
    database: logi_balance_production
    username: <%= ENV["LOGI_BALANCE_DATABASE_USERNAME"] %>
    password: <%= ENV["LOGI_BALANCE_DATABASE_PASSWORD"] %>
    host: logi-balance-db.cxiwycmqimg9.us-west-2.rds.amazonaws.com
  cache:
    <<: *production
  queue:
    <<: *production

